### ISSUE TITLE
Add button to be able to delete and edit groceries from the database

### ISSUE THREAD

**Issue by gobfink** [gobfink/Groceries#7]
Need a way in the UI to be able to delete and edit entries

**Comment by kgustafson** [comment]
This should be only for users with admin privs.  Need to check for admin privs, then give links of commands of Edit/Delete on each row of groceries.  Need to create an edit page in forms.py and add a webservice for grocery/edit/<id>.  Need to add  a webservice for grocery/delete/<id>.  Might be good to add an add grocery as well (maybe) under grocery/add/ .  Need to tie it all up by modifying template under home/grocery/groceries.html

**Comment by gobfink** [comment]
Thats true - If its not too hard we can do the admin authentication with it, but if it is I wouldn't be opposed to a phased approach where maybe we do the edits/deletes and then authentication later (basically because we don't have any public facing instances)

**Comment by kgustafson** [comment]
Completed
